20:10:55.42 [31m[ERROR][0m 1 Exception encountered:

Engine traceback:
  in `test` goal

InvalidFieldException: : Failed to get dependencies for //:root#pandas: The file or directory '3rdparty/python/default.lock' does not exist on disk in the workspace, so the address '3rdparty/python/default.lock:_python-default_lockfile' from the `dependencies` field from the target //:root#pandas cannot be resolved.

